### ISSUE TITLE
点击已插入的公式会报错

### ISSUE THREAD

**Issue by Joe4smu** [hansonGong/math-editor#3]
感谢前面的回复，在新的示例中，点击已插入的公式时还是会报错，以下是示例中的报错信息：

TypeError
elem.className.split is not a function
DomElement.hasClass
https://u9gso4.csb.app/node_modules/wangeditor/dist/wangEditor.js:834:30
HTMLDivElement.eval
https://u9gso4.csb.app/node_modules/wangeditor/dist/wangEditor.js:12082:19
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.
This error overlay is powered by `react-error-overlay` used in `create-react-app`.

**Comment by hansonGong** [comment]
报错信息是wangeditor的报错，没有办法直接定位，能提供个在线demo我看下？还有这些别提issues了，有问题通过QQ：1365408804和我联系吧

**Comment by Joe4smu** [comment]
就是你发的这个，“作为wangeditor菜单”部分：https://codesandbox.io/s/funny-leaf-u9gso4




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月5日(星期四) 下午4:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hansonGong/formula-editor] 点击已插入的公式会报错 (Issue #3)





 
报错信息是wangeditor的报错，没有办法直接定位，能提供个在线demo我看下？还有这些别提issues了，有问题通过QQ：1365408804和我联系吧
