### ISSUE TITLE
npm 引入模式会报错

### ISSUE THREAD

**Issue by jayzch** [hansonGong/math-editor#4]
在非vue3 ，vue2的工程中通过npm引入后，工程似乎无法解析该包。
无论是在vue2的 cli模式的工程，还是纯手工搭建的webpack工程中，均会报错。

`./node_modules/easy-formula-editor/dist/formula-editor.es.js

Module parse failed: Unexpected token (1:7595)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> var e={614:(e,t,n)=>{n.d(t,{Z:()=>a});var i=n(81),s=n.n(i),r=n(645),o=n.n(r)()(s());o.push([e.id,":root {\n  --me-theme: #bcd4e7;\n  --me-theme-light: #d0e3f2;\n  --me-hover: #f1f2f4;\n  --me-border: #ddd;\n  --me-gray: ##666;\n}\n.math-editor {\n  color: #000;\n  font-size: 18px;\n  text-align: left;\n  border: 1px solid #ccc;\n  overflow: hidden;\n}\n.math

./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/backstage/Editable.vue?vue&type=script&lang=js& 13:0-67 25:6-19 45:26-39
 @ ./src/components/backstage/Editable.vue?vue&type=script&lang=js&
 @ ./src/components/backstage/Editable.vue
 @ ./src/route.js
 @ ./src/routers.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.2.128:8018/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

`

**Comment by hansonGong** [comment]
![image](https://user-images.githubusercontent.com/47938757/208413254-5098207a-5907-4211-bfc6-0c4d150d6149.png)
因为打包的是不支持es5版本的，需要在vue.config.js里添加这个配置，这个下周的版本会修复
不好意思，太久没留意到

**Comment by jayzch** [comment]
> ![image](https://user-images.githubusercontent.com/47938757/208413254-5098207a-5907-4211-bfc6-0c4d150d6149.png) 因为打包的是不支持es5版本的，需要在vue.config.js里添加这个配置，这个下周的版本会修复 不好意思，太久没留意到

是引用的工程加这个，还是组件源码工程加这个？
