### ISSUE TITLE
无法设置公式内容进行二次编辑

### ISSUE THREAD

**Issue by zwz** [hansonGong/math-editor#5]
我是将公式编辑器和一个对话框内的dom元素绑定（`editor.create('#dom-in-modal')`）
刚开始对话框是隐藏的（`display:none;`），绑定后开发者工具中是看到公式编辑器相关的dom都是生成好的

然后我会在显示对话框的同时，设置二次编辑内容
```
...
editor.append('x^2')
...
```
但是显示出来后，公式编辑器左侧还是空的

如果我加上一个延时，就可以了
```
...
setTimeout( () =>
editor.append('x^2'), 0)
...
```
请问一下这是什么原因导致的

**Comment by hansonGong** [comment]
实在不好意思，后面如果有什么问题可以通过邮箱或qq和我联系，能给我看下对话框和编辑器这部分你是怎么写的吗？

**Comment by hansonGong** [comment]
这几天会补充回显相关案例
