### ISSUE TITLE
公式编辑框内怎么使用撤回功能Ctr+Z不起作用

### ISSUE THREAD

**Issue by gxhyxb** [hansonGong/math-editor#9]
公式编辑框内怎么使用撤回功能Ctr+Z不起作用

**Comment by gxhyxb** [comment]
have already been solved

**Comment by gxhyxb** [comment]
> 公式编辑框内怎么使用撤回功能Ctr+Z不起作用

Ctr+Z的问题已修复，Ctr+Shift+Z的问题怎么解决？

**Comment by etclub** [comment]
请问你是怎么修复Ctrl+Z的？
复制粘贴这些快捷键都不能用啊
